[package]
name = "vst_effect_template"
version = "0.0.1"
authors = ["Oleg Patsay <opatsay@gmail.com>"]

[dependencies]
vst = { git = "https://github.com/rustaudio/vst-rs" }

[lib]
name = "vst_effect_template"
crate-type = ["cdylib"]